version: "3.8"

services:
  db:
    image: postgres:15
    restart: always # если контейнер упадёт, Docker автоматически его перезапустит.
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh entrypoint.sh
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles 
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data: # Данные сохраняются на хост-машине (вашем компьютере или сервере) в специальном месте, управляемом Docker.
  media_volume:
  static_volume:
