# Generated by Django 4.2.21 on 2025-05-14 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('rarity', models.CharField(choices=[('нормис', 'нормис'), ('с особенностями развития', 'с особенностями развития'), ('смешной', 'смешной'), ('педик', 'педик'), ('никита', 'никита'), ('мега редкий', 'мега редкий'), ('тупой', 'тупой'), ('беспримерный', 'беспримерный'), ('дебильнутый', 'дебильнутый'), ('позитивный', 'позитивный'), ('прикольный', 'прикольный'), ('авторитетный', 'авторитетный'), ('ебырь', 'ебырь'), ('армагидон', 'армагидон')], max_length=50)),
                ('danger', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('power', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('health', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('intelligence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('luck', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
