# Generated by Django 4.2.21 on 2025-05-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_rename_characters_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plans/')),
            ],
        ),
    ]
